In [1]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent
processed_dir = BASE_DIR / "data" / "processed"

lok_df = pd.read_csv(
    processed_dir / "MPLADS_Lok_Sabha_cleaned.csv"
)

rajya_df = pd.read_csv(
    processed_dir / "MPLADS_Rajya_Sabha_cleaned.csv"
)

print("Lok Sabha:", lok_df.shape)
print("Rajya Sabha:", rajya_df.shape)

Lok Sabha: (543, 5)
Rajya Sabha: (231, 5)

In [2]:
print(lok_df.head())
print(rajya_df.head())

   sr_no              state                         mp_name   constituency  \
0      1        Maharashtra  AASHTIKAR PATIL NAGESH BAPURAO        HINGOLI
1      2  Jammu And Kashmir             ABDUL RASHID SHEIKH     BARAMULLAH
2      3              Bihar               ABHAY KUMAR SINHA  AURANGABAD_BR
3      4        West Bengal            ABHIJIT GANGOPADHYAY         TAMLUK
4      5        West Bengal                  Abu Taher Khan    MURSHIDABAD

   allocated_amount
0       190289442.0
1       154773472.1
2       147000000.0
3       147000000.0
4       147000000.0
   sr_no        state                                            mp_name  \
0      1    Telangana    Dr. Abhishek Manu Singhvi (2026-32) (2026-2032)
1      2  Maharashtra  Dr. Ajeet Madhavrao Gopchade (2024-30) (2024-2...
2      3    Rajasthan               Dr. Alka Singh (2026-32) (2026-2032)
3      4   Tamil Nadu        Dr. Anbumani Ramadoss (2026-32) (2026-2032)
4      5  Maharashtra    Dr. Anil Sukhdeorao Bonde (2022-28) (2022-2028)

  member_type  allocated_amount
0  Elected MP        73421449.0
1  Elected MP       147000000.0
2  Elected MP        49000000.0
3  Elected MP        49356476.5
4  Elected MP       196063957.1

In [3]:
print("LOK SABHA ALLOCATION STATISTICS")
print(lok_df["allocated_amount"].describe())

print("\nRAJYA SABHA ALLOCATION STATISTICS")
print(rajya_df["allocated_amount"].describe())

LOK SABHA ALLOCATION STATISTICS
count    5.420000e+02
mean     1.534697e+08
std      2.035116e+07
min      4.900000e+07
25%      1.470000e+08
50%      1.470000e+08
75%      1.478613e+08
max      3.274774e+08
Name: allocated_amount, dtype: float64

RAJYA SABHA ALLOCATION STATISTICS
count    2.310000e+02
mean     1.456211e+08
std      6.848423e+07
min      2.380001e+07
25%      7.350000e+07
50%      1.470000e+08
75%      1.960640e+08
max      3.108990e+08
Name: allocated_amount, dtype: float64

In [4]:
lok_df["house"] = "Lok Sabha"
rajya_df["house"] = "Rajya Sabha"

print(lok_df[["mp_name", "house"]].head())
print()
print(rajya_df[["mp_name", "house"]].head())

                          mp_name      house
0  AASHTIKAR PATIL NAGESH BAPURAO  Lok Sabha
1             ABDUL RASHID SHEIKH  Lok Sabha
2               ABHAY KUMAR SINHA  Lok Sabha
3            ABHIJIT GANGOPADHYAY  Lok Sabha
4                  Abu Taher Khan  Lok Sabha

                                             mp_name        house
0    Dr. Abhishek Manu Singhvi (2026-32) (2026-2032)  Rajya Sabha
1  Dr. Ajeet Madhavrao Gopchade (2024-30) (2024-2...  Rajya Sabha
2               Dr. Alka Singh (2026-32) (2026-2032)  Rajya Sabha
3        Dr. Anbumani Ramadoss (2026-32) (2026-2032)  Rajya Sabha
4    Dr. Anil Sukhdeorao Bonde (2022-28) (2022-2028)  Rajya Sabha

In [5]:
lok_mean = lok_df["allocated_amount"].mean()
rajya_mean = rajya_df["allocated_amount"].mean()

lok_df["allocation_vs_mean"] = (
    lok_df["allocated_amount"] - lok_mean
)

rajya_df["allocation_vs_mean"] = (
    rajya_df["allocated_amount"] - rajya_mean
)

In [6]:
lok_df["allocation_pct_from_mean"] = (
    (lok_df["allocated_amount"] - lok_mean) / lok_mean
) * 100

rajya_df["allocation_pct_from_mean"] = (
    (rajya_df["allocated_amount"] - rajya_mean) / rajya_mean
) * 100

In [7]:
print("LOK SABHA")
display(
    lok_df[
        [
            "mp_name",
            "state",
            "allocated_amount",
            "allocation_vs_mean",
            "allocation_pct_from_mean"
        ]
    ].head()
)

print("\nRAJYA SABHA")
display(
    rajya_df[
        [
            "mp_name",
            "state",
            "allocated_amount",
            "allocation_vs_mean",
            "allocation_pct_from_mean"
        ]
    ].head()
)

LOK SABHA

,mp_name,state,allocated_amount,allocation_vs_mean,allocation_pct_from_mean
0,AASHTIKAR PATIL NAGESH BAPURAO,Maharashtra,190289442.0,3.681979e+07,23.991574
1,ABDUL RASHID SHEIKH,Jammu And Kashmir,154773472.1,1.303817e+06,0.849560
2,ABHAY KUMAR SINHA,Bihar,147000000.0,-6.469656e+06,-4.215593
3,ABHIJIT GANGOPADHYAY,West Bengal,147000000.0,-6.469656e+06,-4.215593
4,Abu Taher Khan,West Bengal,147000000.0,-6.469656e+06,-4.215593

RAJYA SABHA

,mp_name,state,allocated_amount,allocation_vs_mean,allocation_pct_from_mean
0,Dr. Abhishek Manu Singhvi (2026-32) (2026-2032),Telangana,73421449.0,-7.219969e+07,-49.580500
1,Dr. Ajeet Madhavrao Gopchade (2024-30) (2024-2...,Maharashtra,147000000.0,1.378864e+06,0.946885
2,Dr. Alka Singh (2026-32) (2026-2032),Rajasthan,49000000.0,-9.662114e+07,-66.351038
3,Dr. Anbumani Ramadoss (2026-32) (2026-2032),Tamil Nadu,49356476.5,-9.626466e+07,-66.106241
4,Dr. Anil Sukhdeorao Bonde (2022-28) (2022-2028),Maharashtra,196063957.1,5.044282e+07,34.639767

In [8]:
# State-wise average allocation

lok_state_mean = (
    lok_df.groupby("state")["allocated_amount"]
    .transform("mean")
)

rajya_state_mean = (
    rajya_df.groupby("state")["allocated_amount"]
    .transform("mean")
)

lok_df["state_avg_allocation"] = lok_state_mean
rajya_df["state_avg_allocation"] = rajya_state_mean

In [9]:
lok_df["allocation_vs_state_avg"] = (
    lok_df["allocated_amount"] - lok_df["state_avg_allocation"]
)

rajya_df["allocation_vs_state_avg"] = (
    rajya_df["allocated_amount"] - rajya_df["state_avg_allocation"]
)

In [10]:
lok_df["allocation_pct_from_state_avg"] = (
    lok_df["allocation_vs_state_avg"]
    / lok_df["state_avg_allocation"]
) * 100

rajya_df["allocation_pct_from_state_avg"] = (
    rajya_df["allocation_vs_state_avg"]
    / rajya_df["state_avg_allocation"]
) * 100

In [11]:
print("LOK SABHA")
display(
    lok_df[
        [
            "mp_name",
            "state",
            "allocated_amount",
            "state_avg_allocation",
            "allocation_vs_state_avg",
            "allocation_pct_from_state_avg"
        ]
    ].head(10)
)

print("\nRAJYA SABHA")
display(
    rajya_df[
        [
            "mp_name",
            "state",
            "allocated_amount",
            "state_avg_allocation",
            "allocation_vs_state_avg",
            "allocation_pct_from_state_avg"
        ]
    ].head(10)
)

LOK SABHA

,mp_name,state,allocated_amount,state_avg_allocation,allocation_vs_state_avg,allocation_pct_from_state_avg
0,AASHTIKAR PATIL NAGESH BAPURAO,Maharashtra,190289442.0,1.529643e+08,3.732517e+07,24.401233
1,ABDUL RASHID SHEIKH,Jammu And Kashmir,154773472.1,1.485547e+08,6.218778e+06,4.186187
2,ABHAY KUMAR SINHA,Bihar,147000000.0,1.499866e+08,-2.986563e+06,-1.991220
3,ABHIJIT GANGOPADHYAY,West Bengal,147000000.0,1.521746e+08,-5.174601e+06,-3.400437
4,Abu Taher Khan,West Bengal,147000000.0,1.521746e+08,-5.174601e+06,-3.400437
5,ADHIKARI SOUMENDU,West Bengal,147000000.0,1.521746e+08,-5.174601e+06,-3.400437
6,ADITYA YADAV,Uttar Pradesh,147000000.0,1.513970e+08,-4.396955e+06,-2.904256
7,Adv Adoor Prakash,Kerala,147000000.0,1.555437e+08,-8.543716e+06,-5.492807
8,Adv Dean Kuriakose,Kerala,147000000.0,1.555437e+08,-8.543716e+06,-5.492807
9,ADV GOWAAL KAGADA PADAVI,Maharashtra,147816309.1,1.529643e+08,-5.147964e+06,-3.365468

RAJYA SABHA

,mp_name,state,allocated_amount,state_avg_allocation,allocation_vs_state_avg,allocation_pct_from_state_avg
0,Dr. Abhishek Manu Singhvi (2026-32) (2026-2032),Telangana,73421449.0,1.674064e+08,-9.398497e+07,-56.141795
1,Dr. Ajeet Madhavrao Gopchade (2024-30) (2024-2...,Maharashtra,147000000.0,1.211395e+08,2.586047e+07,21.347671
2,Dr. Alka Singh (2026-32) (2026-2032),Rajasthan,49000000.0,1.372256e+08,-8.822558e+07,-64.292372
3,Dr. Anbumani Ramadoss (2026-32) (2026-2032),Tamil Nadu,49356476.5,1.217507e+08,-7.239423e+07,-59.461036
4,Dr. Anil Sukhdeorao Bonde (2022-28) (2022-2028),Maharashtra,196063957.1,1.211395e+08,7.492443e+07,61.849691
5,Dr. Ashok Kumar Mittal (2022-28) (2022-2028),Punjab,222487632.1,1.938457e+08,2.864196e+07,14.775654
6,Dr. Bhim Singh (2024-30) (2024-2030),Bihar,186200000.0,1.676016e+08,1.859839e+07,11.096784
7,Dr. Dharmasthala Veerendra Heggade (2022-28) (...,Karnataka,196063957.1,1.404611e+08,5.560282e+07,39.585907
8,Dr. Dharmshila Gupta (2024-30) (2024-2030),Bihar,186200000.0,1.676016e+08,1.859839e+07,11.096784
9,Dr. Dinesh Sharma (2023-26) (2023-2026),Uttar Pradesh,147000000.0,1.829292e+08,-3.592922e+07,-19.641050

In [12]:
# Calculate allocation Z-scores

lok_std = lok_df["allocated_amount"].std()
rajya_std = rajya_df["allocated_amount"].std()

lok_df["allocation_zscore"] = (
    (lok_df["allocated_amount"] - lok_mean) / lok_std
)

rajya_df["allocation_zscore"] = (
    (rajya_df["allocated_amount"] - rajya_mean) / rajya_std
)

print("Z-score features created successfully.")

Z-score features created successfully.

In [13]:
print("===== TOP 10 MOST UNUSUAL LOK SABHA ALLOCATIONS =====")

display(
    lok_df.loc[
        lok_df["allocation_zscore"].abs().sort_values(ascending=False).index,
        ["mp_name", "state", "allocated_amount", "allocation_zscore"]
    ].head(10)
)

print("===== TOP 10 MOST UNUSUAL RAJYA SABHA ALLOCATIONS =====")

display(
    rajya_df.loc[
        rajya_df["allocation_zscore"].abs().sort_values(ascending=False).index,
        ["mp_name", "state", "allocated_amount", "allocation_zscore"]
    ].head(10)
)

===== TOP 10 MOST UNUSUAL LOK SABHA ALLOCATIONS =====

,mp_name,state,allocated_amount,allocation_zscore
167,EATALA RAJENDER,Telangana,327477390.9,8.550260
50,Arvind Dharmapuri,Telangana,281396355.1,6.285965
56,Asit Kumar Mal,West Bengal,275694456.7,6.005790
412,Saptagiri Sankar Ulaka,Odisha,269500000.0,5.701411
380,Ramesh Chandappa Jigajinagi,Karnataka,269500000.0,5.701411
156,DR. RAJESH MISHRA,Madhya Pradesh,262724510.4,5.368482
473,SK NURUL ISLAM,West Bengal,49000000.0,-5.133351
524,VARUN CHAUDHRY,Haryana,255454264.0,5.011243
323,PATEL UMESHBHAI BABUBHAI,The Dadra And Nagar Haveli And Daman And Diu,245063957.0,4.500692
248,KONDA VISHWESHWAR REDDY,Telangana,233721421.0,3.943351

===== TOP 10 MOST UNUSUAL RAJYA SABHA ALLOCATIONS =====

,mp_name,state,allocated_amount,allocation_zscore
41,Shri Abdul Wahab (2021-27) (2021-2027),Kerala,310898953.3,2.413371
169,Shri S. Selvaganabathy (2021-27) (2021-2027),Puducherry,292881856.5,2.150287
34,Dr. V. Sivadasan (2021-27) (2021-2027),Kerala,276720323.3,1.914298
151,Shri Rajeev Shukla (2022-28) (2022-2028),Chhattisgarh,271174394.2,1.833316
69,Shri Debashish Samantaray (2026-30) (2026-2030),Odisha,23800006.0,-1.778820
104,Shri Khiangte Laltluangkima (2026-32) (2026-2032),Mizoram,24500000.0,-1.768599
51,Shri Ashwini Vaishnaw (2024-30) (2024-2030),Odisha,265563957.1,1.751393
147,Shri R. Dharmar (2022-28) (2022-2028),Tamil Nadu,260812242.5,1.682009
219,Smt. Ranjeet Ranjan (2022-28) (2022-2028),Chhattisgarh,246780257.9,1.477116
11,Dr. John Brittas (2021-27) (2021-2027),Kerala,245063957.1,1.452054

In [14]:
# Create Z-score based anomaly flags

lok_df["zscore_anomaly"] = (
    lok_df["allocation_zscore"].abs() > 3
)

rajya_df["zscore_anomaly"] = (
    rajya_df["allocation_zscore"].abs() > 3
)

print("Lok Sabha anomalies:", lok_df["zscore_anomaly"].sum())
print("Rajya Sabha anomalies:", rajya_df["zscore_anomaly"].sum())

Lok Sabha anomalies: 12
Rajya Sabha anomalies: 0

In [15]:
print("===== FLAGGED LOK SABHA RECORDS =====")

display(
    lok_df[
        lok_df["zscore_anomaly"]
    ][
        [
            "mp_name",
            "state",
            "allocated_amount",
            "allocation_zscore"
        ]
    ].sort_values(
        "allocation_zscore",
        ascending=False
    )
)

print("===== FLAGGED RAJYA SABHA RECORDS =====")

display(
    rajya_df[
        rajya_df["zscore_anomaly"]
    ][
        [
            "mp_name",
            "state",
            "allocated_amount",
            "allocation_zscore"
        ]
    ].sort_values(
        "allocation_zscore",
        ascending=False
    )
)

===== FLAGGED LOK SABHA RECORDS =====

,mp_name,state,allocated_amount,allocation_zscore
167,EATALA RAJENDER,Telangana,327477390.9,8.550260
50,Arvind Dharmapuri,Telangana,281396355.1,6.285965
56,Asit Kumar Mal,West Bengal,275694456.7,6.005790
380,Ramesh Chandappa Jigajinagi,Karnataka,269500000.0,5.701411
412,Saptagiri Sankar Ulaka,Odisha,269500000.0,5.701411
156,DR. RAJESH MISHRA,Madhya Pradesh,262724510.4,5.368482
524,VARUN CHAUDHRY,Haryana,255454264.0,5.011243
323,PATEL UMESHBHAI BABUBHAI,The Dadra And Nagar Haveli And Daman And Diu,245063957.0,4.500692
248,KONDA VISHWESHWAR REDDY,Telangana,233721421.0,3.943351
285,Manoj Tiwari,Delhi,225843858.0,3.556269
11,AFZAL ANSARI,Uttar Pradesh,220500000.0,3.293686
473,SK NURUL ISLAM,West Bengal,49000000.0,-5.133351

===== FLAGGED RAJYA SABHA RECORDS =====

Empty DataFrame
Columns: [mp_name, state, allocated_amount, allocation_zscore]
Index: []

In [16]:
def assign_risk_level(z):
    if pd.isna(z):
        return "Unknown"
    elif abs(z) > 3:
        return "High"
    elif abs(z) > 2:
        return "Medium"
    else:
        return "Low"


lok_df["risk_level"] = lok_df["allocation_zscore"].apply(assign_risk_level)
rajya_df["risk_level"] = rajya_df["allocation_zscore"].apply(assign_risk_level)

print("Lok Sabha risk levels:")
print(lok_df["risk_level"].value_counts())

print("\nRajya Sabha risk levels:")
print(rajya_df["risk_level"].value_counts())

Lok Sabha risk levels:
risk_level
Low        515
Medium      15
High        12
Unknown      1
Name: count, dtype: int64

Rajya Sabha risk levels:
risk_level
Low       229
Medium      2
Name: count, dtype: int64

In [17]:
print("===== HIGH-RISK LOK SABHA RECORDS =====")

display(
    lok_df[lok_df["risk_level"] == "High"][
        [
            "mp_name",
            "state",
            "allocated_amount",
            "allocation_zscore",
            "risk_level"
        ]
    ].sort_values("allocation_zscore", ascending=False)
)

print("===== HIGH-RISK RAJYA SABHA RECORDS =====")

display(
    rajya_df[rajya_df["risk_level"] == "High"][
        [
            "mp_name",
            "state",
            "allocated_amount",
            "allocation_zscore",
            "risk_level"
        ]
    ].sort_values("allocation_zscore", ascending=False)
)

===== HIGH-RISK LOK SABHA RECORDS =====

,mp_name,state,allocated_amount,allocation_zscore,risk_level
167,EATALA RAJENDER,Telangana,327477390.9,8.550260,High
50,Arvind Dharmapuri,Telangana,281396355.1,6.285965,High
56,Asit Kumar Mal,West Bengal,275694456.7,6.005790,High
380,Ramesh Chandappa Jigajinagi,Karnataka,269500000.0,5.701411,High
412,Saptagiri Sankar Ulaka,Odisha,269500000.0,5.701411,High
156,DR. RAJESH MISHRA,Madhya Pradesh,262724510.4,5.368482,High
524,VARUN CHAUDHRY,Haryana,255454264.0,5.011243,High
323,PATEL UMESHBHAI BABUBHAI,The Dadra And Nagar Haveli And Daman And Diu,245063957.0,4.500692,High
248,KONDA VISHWESHWAR REDDY,Telangana,233721421.0,3.943351,High
285,Manoj Tiwari,Delhi,225843858.0,3.556269,High
11,AFZAL ANSARI,Uttar Pradesh,220500000.0,3.293686,High
473,SK NURUL ISLAM,West Bengal,49000000.0,-5.133351,High

===== HIGH-RISK RAJYA SABHA RECORDS =====

Empty DataFrame
Columns: [mp_name, state, allocated_amount, allocation_zscore, risk_level]
Index: []

In [18]:
def get_anomaly_reason(z):
    if pd.isna(z):
        return "Allocation amount is missing"

    elif z > 3:
        return "Allocation significantly above the normal range"

    elif z < -3:
        return "Allocation significantly below the normal range"

    elif z > 2:
        return "Allocation moderately above the normal range"

    elif z < -2:
        return "Allocation moderately below the normal range"

    else:
        return "Allocation within the normal range"


lok_df["anomaly_reason"] = lok_df["allocation_zscore"].apply(
    get_anomaly_reason
)

rajya_df["anomaly_reason"] = rajya_df["allocation_zscore"].apply(
    get_anomaly_reason
)

print("Explainable anomaly reasons added successfully.")

Explainable anomaly reasons added successfully.

In [19]:
print("===== LOK SABHA EXPLANATION CHECK =====")

display(
    lok_df[
        [
            "mp_name",
            "allocated_amount",
            "allocation_zscore",
            "risk_level",
            "anomaly_reason"
        ]
    ].sort_values(
        "allocation_zscore",
        ascending=False
    ).head(15)
)

===== LOK SABHA EXPLANATION CHECK =====

,mp_name,allocated_amount,allocation_zscore,risk_level,anomaly_reason
167,EATALA RAJENDER,327477390.9,8.550260,High,Allocation significantly above the normal range
50,Arvind Dharmapuri,281396355.1,6.285965,High,Allocation significantly above the normal range
56,Asit Kumar Mal,275694456.7,6.005790,High,Allocation significantly above the normal range
380,Ramesh Chandappa Jigajinagi,269500000.0,5.701411,High,Allocation significantly above the normal range
412,Saptagiri Sankar Ulaka,269500000.0,5.701411,High,Allocation significantly above the normal range
156,DR. RAJESH MISHRA,262724510.4,5.368482,High,Allocation significantly above the normal range
524,VARUN CHAUDHRY,255454264.0,5.011243,High,Allocation significantly above the normal range
323,PATEL UMESHBHAI BABUBHAI,245063957.0,4.500692,High,Allocation significantly above the normal range
248,KONDA VISHWESHWAR REDDY,233721421.0,3.943351,High,Allocation significantly above the normal range
285,Manoj Tiwari,225843858.0,3.556269,High,Allocation significantly above the normal range
11,AFZAL ANSARI,220500000.0,3.293686,High,Allocation significantly above the normal range
522,Vaithilingam Ve,209368972.1,2.746738,Medium,Allocation moderately above the normal range
374,RAM PRASAD CHAUDHARY,204176957.1,2.491617,Medium,Allocation moderately above the normal range
239,KARTICK CHANDRA PAUL,202677986.6,2.417962,Medium,Allocation moderately above the normal range
98,C.M.RAMESH,202531656.1,2.410771,Medium,Allocation moderately above the normal range

In [20]:
print("===== LOK SABHA FEATURE CHECK =====")
print("Shape:", lok_df.shape)
print("\nColumns:")
print(lok_df.columns.tolist())
print("\nMissing values:")
print(lok_df.isnull().sum())

print("\n" + "=" * 50)

print("===== RAJYA SABHA FEATURE CHECK =====")
print("Shape:", rajya_df.shape)
print("\nColumns:")
print(rajya_df.columns.tolist())
print("\nMissing values:")
print(rajya_df.isnull().sum())

===== LOK SABHA FEATURE CHECK =====
Shape: (543, 15)

Columns:
['sr_no', 'state', 'mp_name', 'constituency', 'allocated_amount', 'house', 'allocation_vs_mean', 'allocation_pct_from_mean', 'state_avg_allocation', 'allocation_vs_state_avg', 'allocation_pct_from_state_avg', 'allocation_zscore', 'zscore_anomaly', 'risk_level', 'anomaly_reason']

Missing values:
sr_no                            0
state                            0
mp_name                          0
constituency                     0
allocated_amount                 1
house                            0
allocation_vs_mean               1
allocation_pct_from_mean         1
state_avg_allocation             0
allocation_vs_state_avg          1
allocation_pct_from_state_avg    1
allocation_zscore                1
zscore_anomaly                   0
risk_level                       0
anomaly_reason                   0
dtype: int64

==================================================
===== RAJYA SABHA FEATURE CHECK =====
Shape: (231, 15)

Columns:
['sr_no', 'state', 'mp_name', 'member_type', 'allocated_amount', 'house', 'allocation_vs_mean', 'allocation_pct_from_mean', 'state_avg_allocation', 'allocation_vs_state_avg', 'allocation_pct_from_state_avg', 'allocation_zscore', 'zscore_anomaly', 'risk_level', 'anomaly_reason']

Missing values:
sr_no                            0
state                            0
mp_name                          0
member_type                      0
allocated_amount                 0
house                            0
allocation_vs_mean               0
allocation_pct_from_mean         0
state_avg_allocation             0
allocation_vs_state_avg          0
allocation_pct_from_state_avg    0
allocation_zscore                0
zscore_anomaly                   0
risk_level                       0
anomaly_reason                   0
dtype: int64

In [21]:
# Create path for ML-ready data

ml_ready_dir = BASE_DIR / "data" / "ml_ready"

ml_ready_dir.mkdir(exist_ok=True)

In [22]:
lok_ml_path = ml_ready_dir / "MPLADS_Lok_Sabha_ml_ready.csv"
rajya_ml_path = ml_ready_dir / "MPLADS_Rajya_Sabha_ml_ready.csv"

lok_df.to_csv(lok_ml_path, index=False)
rajya_df.to_csv(rajya_ml_path, index=False)

print("Files saved successfully!")
print(lok_ml_path)
print(rajya_ml_path)

Files saved successfully!
C:\Users\gpran\Desktop\MPLADS\data\ml_ready\MPLADS_Lok_Sabha_ml_ready.csv
C:\Users\gpran\Desktop\MPLADS\data\ml_ready\MPLADS_Rajya_Sabha_ml_ready.csv

In [23]:
print(list(ml_ready_dir.iterdir()))

[WindowsPath('C:/Users/gpran/Desktop/MPLADS/data/ml_ready/MPLADS_Lok_Sabha_ml_ready.csv'), WindowsPath('C:/Users/gpran/Desktop/MPLADS/data/ml_ready/MPLADS_Rajya_Sabha_ml_ready.csv')]